#!/usr/bin/tclsh

proc colors {idx bg fg} {
  set ::bg($idx) $::ansi(bg$bg)
  set ::fgi($idx) $::ansi(fg$bg)
  set ::fg($idx) $::ansi(fg$fg)
}

set ansi(reset) {\[\e[0m\]}
set ansi(fgreset) {\[\e[39m\]}
set ansi(fg0) {\[\e[30m\]}
set ansi(fg1) {\[\e[31m\]}
set ansi(fg2) {\[\e[32m\]}
set ansi(fg3) {\[\e[33m\]}
set ansi(fg4) {\[\e[34m\]}
set ansi(fg5) {\[\e[35m\]}
set ansi(fg6) {\[\e[36m\]}
set ansi(fg7) {\[\e[37m\]}
set ansi(fg8) {\[\e[90m\]}
set ansi(fg9) {\[\e[91m\]}
set ansi(fg10) {\[\e[92m\]}
set ansi(fg11) {\[\e[93m\]}
set ansi(fg12) {\[\e[94m\]}
set ansi(fg13) {\[\e[95m\]}
set ansi(fg14) {\[\e[96m\]}
set ansi(fg15) {\[\e[97m\]}
set ansi(bgreset) {\[\e[49m\]}
set ansi(bg0) {\[\e[40m\]}
set ansi(bg1) {\[\e[41m\]}
set ansi(bg2) {\[\e[42m\]}
set ansi(bg3) {\[\e[43m\]}
set ansi(bg4) {\[\e[44m\]}
set ansi(bg5) {\[\e[45m\]}
set ansi(bg6) {\[\e[46m\]}
set ansi(bg7) {\[\e[47m\]}
set ansi(bg8) {\[\e[100m\]}
set ansi(bg9) {\[\e[101m\]}
set ansi(bg10) {\[\e[102m\]}
set ansi(bg11) {\[\e[103m\]}
set ansi(bg12) {\[\e[104m\]}
set ansi(bg13) {\[\e[105m\]}
set ansi(bg14) {\[\e[106m\]}
set ansi(bg15) {\[\e[107m\]}

set icons(cli) "\ue7a2"
set icons(powerline) "\ue0bc"
set icons(powerline2) "\ue0bd"
set icons(bolt) "\uf0e7"
set icons(bolt2) "\u26a1"
set icons(host) "\uf108"
set icons(date) "\uf073"
set icons(time) "\uf017"
set icons(dir) "\uf0a0"

colors cli 8 14
colors cliroot 8 2
colors host 13 8
colors hostroot 0 2
colors date 10 14
colors time 6 8
colors dir 14 8

if {$tcl_platform(user) eq "root"} {
  set fg(cli) $fg(cliroot)
  set fgi(cli) $fgi(cliroot)
  set bg(cli) $bg(cliroot)
  set bg(host) $bg(hostroot)
  set fgi(host) $fgi(hostroot)
  set fg(host) $fg(hostroot)
}

set hostname [lindex [split [exec hostname] "."] 0]
set now [clock seconds]
set width [lindex [exec stty size] 1]
set maxdirwidth [expr $width-[string length $hostname]-42]
set dir [lindex [split [pwd] "/"] end]
if {[string length $dir] > $maxdirwidth} {
  set dir "[string range $dir 0 [expr $maxdirwidth-4]]..."
}

append prompt "$bg(cli)  $fgi(cli)"
append prompt "$bg(host)$icons(powerline)$fg(host) $icons(host) $hostname $fgi(host)"
append prompt "$bg(date)$icons(powerline)$fg(date) $icons(date) [clock format $now -format %Y$icons(powerline2)%m$icons(powerline2)%d$icons(powerline2)%a] $fgi(date)"
append prompt "$bg(time)$icons(powerline)$fg(time) $icons(time) [clock format $now -format %R] $fgi(time)"
append prompt "$bg(dir)$icons(powerline)$fg(dir) $icons(dir) $dir $fgi(dir)"
append prompt "$ansi(bgreset)$icons(powerline)\n"
append prompt "$bg(cli)$fg(cli)$icons(cli)$ansi(bgreset)$fgi(cli)$icons(powerline)$ansi(fgreset) "
puts -nonewline $prompt
